version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: kaimono-kanri-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kaimono_kanri
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
